awsiotEndpoint = "xxxxxxxxxxxxxxxxxxx-ats.iot.eu-central-1.amazonaws.com"
rootCAPath = "certs/aws-root-ca.pem"
certificatePath = "certs/certificate.pem.crt"
privateKeyPath = "certs/private.pem.key"
thingName = "ESP32DevKitC"